// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class Activity
    {
        public Activity()
        {
            UserActivity = new HashSet<UserActivity>();
        }

        [Key]
        public short ActivityId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("Activity")]
        public virtual ICollection<UserActivity> UserActivity { get; set; }
    }
}