// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayDating.DataAccess.Models
{
    [Index("AzureAdB2cobjectId", Name = "UI_ApplicationUser_AzureAdB2CObjectId", IsUnique = true)]
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            UserActivity = new HashSet<UserActivity>();
            UserEyesColorPreference = new HashSet<UserEyesColorPreference>();
            UserFeedback = new HashSet<UserFeedback>();
            UserHairColorPreference = new HashSet<UserHairColorPreference>();
            UserInvitation = new HashSet<UserInvitation>();
            UserMessageFromApplicationUser = new HashSet<UserMessage>();
            UserMessageToApplicationUser = new HashSet<UserMessage>();
            UserPhoto = new HashSet<UserPhoto>();
            UserProfile = new HashSet<UserProfile>();
            UserReligionPreference = new HashSet<UserReligionPreference>();
        }

        [Key]
        public long ApplicationUserId { get; set; }
        [Required]
        [StringLength(150)]
        public string FullName { get; set; }
        [Required]
        [StringLength(150)]
        public string EmailAddress { get; set; }
        public DateTimeOffset LastLogIn { get; set; }
        [Column("AzureAdB2CObjectId")]
        public Guid AzureAdB2cobjectId { get; set; }
        [Column(TypeName = "money")]
        public decimal AvailableFunds { get; set; }

        [InverseProperty("ApplicationUser")]
        public virtual ApplicationUserRole ApplicationUserRole { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserActivity> UserActivity { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserEyesColorPreference> UserEyesColorPreference { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserFeedback> UserFeedback { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserHairColorPreference> UserHairColorPreference { get; set; }
        [InverseProperty("InvitingApplicationUser")]
        public virtual ICollection<UserInvitation> UserInvitation { get; set; }
        [InverseProperty("FromApplicationUser")]
        public virtual ICollection<UserMessage> UserMessageFromApplicationUser { get; set; }
        [InverseProperty("ToApplicationUser")]
        public virtual ICollection<UserMessage> UserMessageToApplicationUser { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserPhoto> UserPhoto { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
        [InverseProperty("ApplicationUser")]
        public virtual ICollection<UserReligionPreference> UserReligionPreference { get; set; }
    }
}