// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class DateObjective
    {
        public DateObjective()
        {
            UserProfile = new HashSet<UserProfile>();
        }

        [Key]
        public short DateObjectiveId { get; set; }
        [Required]
        [StringLength(20)]
        public string Name { get; set; }

        [InverseProperty("CurrentDateObjective")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}