// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayDating.DataAccess.Models
{
    public partial class EyesColor
    {
        public EyesColor()
        {
            UserProfileEyesColor = new HashSet<UserProfile>();
            UserProfilePreferredEyesColor = new HashSet<UserProfile>();
        }

        [Key]
        public short EyesColorId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("EyesColor")]
        public virtual ICollection<UserProfile> UserProfileEyesColor { get; set; }
        [InverseProperty("PreferredEyesColor")]
        public virtual ICollection<UserProfile> UserProfilePreferredEyesColor { get; set; }
    }
}