// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class EyesColor
    {
        public EyesColor()
        {
            UserEyesColorPreference = new HashSet<UserEyesColorPreference>();
            UserProfile = new HashSet<UserProfile>();
        }

        [Key]
        public short EyesColorId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("EyesColor")]
        public virtual ICollection<UserEyesColorPreference> UserEyesColorPreference { get; set; }
        [InverseProperty("EyesColor")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}