// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayDating.DataAccess.Models
{
    public partial class Gender
    {
        public Gender()
        {
            UserProfile = new HashSet<UserProfile>();
        }

        [Key]
        public short GenderId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Name { get; set; }

        [InverseProperty("BiologicalGender")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}