// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayDating.DataAccess.Models
{
    public partial class HairColor
    {
        public HairColor()
        {
            UserProfileHairColor = new HashSet<UserProfile>();
            UserProfilePreferredHairColor = new HashSet<UserProfile>();
        }

        [Key]
        public short HairColorId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("HairColor")]
        public virtual ICollection<UserProfile> UserProfileHairColor { get; set; }
        [InverseProperty("PreferredHairColor")]
        public virtual ICollection<UserProfile> UserProfilePreferredHairColor { get; set; }
    }
}