// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class HairColor
    {
        public HairColor()
        {
            UserHairColorPreference = new HashSet<UserHairColorPreference>();
            UserProfile = new HashSet<UserProfile>();
        }

        [Key]
        public short HairColorId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("HairColor")]
        public virtual ICollection<UserHairColorPreference> UserHairColorPreference { get; set; }
        [InverseProperty("HairColor")]
        public virtual ICollection<UserProfile> UserProfile { get; set; }
    }
}