// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayDating.DataAccess.Models
{
    public partial class KidStatus
    {
        public KidStatus()
        {
            UserProfileKidStatus = new HashSet<UserProfile>();
            UserProfilePreferredKidStatus = new HashSet<UserProfile>();
        }

        [Key]
        public short KidStatusId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("KidStatus")]
        public virtual ICollection<UserProfile> UserProfileKidStatus { get; set; }
        [InverseProperty("PreferredKidStatus")]
        public virtual ICollection<UserProfile> UserProfilePreferredKidStatus { get; set; }
    }
}