// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayDating.DataAccess.Models
{
    [Index("Name", Name = "UI_TattooStatus_Name", IsUnique = true)]
    public partial class TattooStatus
    {
        public TattooStatus()
        {
            UserProfilePreferredTattooStatus = new HashSet<UserProfile>();
            UserProfileTattooStatus = new HashSet<UserProfile>();
        }

        [Key]
        public short TattooStatusId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("PreferredTattooStatus")]
        public virtual ICollection<UserProfile> UserProfilePreferredTattooStatus { get; set; }
        [InverseProperty("TattooStatus")]
        public virtual ICollection<UserProfile> UserProfileTattooStatus { get; set; }
    }
}