// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class UserProfile
    {
        [Key]
        public long UserProfileId { get; set; }
        public long ApplicationUserId { get; set; }
        [Required]
        [StringLength(100)]
        public string About { get; set; }
        public short HairColorId { get; set; }
        public short EyesColorId { get; set; }
        public short KidStatusId { get; set; }
        public short PreferredKidStatusId { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserProfile")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(EyesColorId))]
        [InverseProperty("UserProfile")]
        public virtual EyesColor EyesColor { get; set; }
        [ForeignKey(nameof(HairColorId))]
        [InverseProperty("UserProfile")]
        public virtual HairColor HairColor { get; set; }
        [ForeignKey(nameof(KidStatusId))]
        [InverseProperty("UserProfileKidStatus")]
        public virtual KidStatus KidStatus { get; set; }
        [ForeignKey(nameof(PreferredKidStatusId))]
        [InverseProperty("UserProfilePreferredKidStatus")]
        public virtual KidStatus PreferredKidStatus { get; set; }
    }
}