// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    [Index(nameof(ApplicationUserId), nameof(ActivityId), Name = "UI_UserActivity_ApplicationUserId_ActivityId", IsUnique = true)]
    public partial class UserActivity
    {
        [Key]
        public long UserActivityId { get; set; }
        public long ApplicationUserId { get; set; }
        public short ActivityId { get; set; }
        public short FrequencyId { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty("UserActivity")]
        public virtual Activity Activity { get; set; }
        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserActivity")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(FrequencyId))]
        [InverseProperty("UserActivity")]
        public virtual Frequency Frequency { get; set; }
    }
}