// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class UserEyesColorPreference
    {
        [Key]
        public long UserEyesColorPreferenceId { get; set; }
        public long ApplicationUserId { get; set; }
        public short EyesColorId { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserEyesColorPreference")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(EyesColorId))]
        [InverseProperty("UserEyesColorPreference")]
        public virtual EyesColor EyesColor { get; set; }
    }
}