// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class UserHairColorPreference
    {
        [Key]
        public long UserHairColorPreferenceId { get; set; }
        public long ApplicationUserId { get; set; }
        public short HairColorId { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserHairColorPreference")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(HairColorId))]
        [InverseProperty("UserHairColorPreference")]
        public virtual HairColor HairColor { get; set; }
    }
}