// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FairPlayDating.DataAccess.Models
{
    public partial class UserReligionPreference
    {
        [Key]
        public int UserReligionPreferenceId { get; set; }
        public long ApplicationUserId { get; set; }
        public short ReligionId { get; set; }

        [ForeignKey(nameof(ApplicationUserId))]
        [InverseProperty("UserReligionPreference")]
        public virtual ApplicationUser ApplicationUser { get; set; }
        [ForeignKey(nameof(ReligionId))]
        [InverseProperty("UserReligionPreference")]
        public virtual Religion Religion { get; set; }
    }
}